This is Assignment1
tejashrighogare/SDETAssignment pull request #1
Opened 2023-03-09 09:30 UTC by tejashrighogare

2023-03-10 09:21 UTC, vrushalee123 commented on Assignment1/SDETAssignment/src/Occurances/Occurancesassign.java
> +	public static void main(String args[])
Please do code indentation

2023-03-13 15:21 UTC, amitsahu8 requested changes

2023-03-13 15:21 UTC, amitsahu8 commented on Assignment1/SDETAssignment/src/Occurances/Occurancesassign.java
> +	{
need to discuss

2023-03-14 07:10 UTC, tejashrighogare commented on Assignment1/SDETAssignment/src/Occurances/Occurancesassign.java
> +	public static void main(String args[])
Yes

2023-03-14 07:11 UTC, tejashrighogare commented on Assignment1/SDETAssignment/src/Occurances/Occurancesassign.java
> +	{
Yes, sure

2023-03-17 07:33 UTC, amitsahu8 requested changes

2023-03-17 07:33 UTC, amitsahu8 commented on arrayJava.java
> +			a[0]=10;
remove extra spaces and format the code

2023-03-17 07:33 UTC, amitsahu8 commented on arrayMultidimensional.java
> +		System.out.println("The 2D array is: ");
no need of second for loop, print the array in first for loop

2023-03-17 07:33 UTC, amitsahu8 commented on ifElseIf.java
> +			System.out.println("city is meerut");
code format issue

2023-03-17 07:33 UTC, amitsahu8 commented on sortColour.java
> +
remove extra spaces

2023-03-17 07:33 UTC, amitsahu8 commented on timeDifference.java
> +		System.out.println("Time in minutes: " + diffMinutes + " minutes.");
Print text should be "Time differences in minutes: "

2023-03-17 07:33 UTC, amitsahu8 commented on timeDifference.java
> +			time2="24:00";
parameterize the code means write the code is different method and call it in main

2023-03-27 06:42 UTC, merged