Testing2
tejashrighogare/SDETAssignment pull request #2
Opened 2023-03-13 07:31 UTC by tejashrighogare

2023-03-17 07:39 UTC, amitsahu8 requested changes

2023-03-17 07:39 UTC, amitsahu8 commented on Assignment1/Occurancesassign.java
> +		int count = 0;
Logic is not proper. Write the core logic in different method and parameterize it. Also logic should be generic.

2023-03-17 07:39 UTC, amitsahu8 commented on Assignment2/Assignment2.java
> +String inElement=Elements.get(1);
code format issue

2023-03-17 07:39 UTC, amitsahu8 commented on Assignment2/Assignment2.java
> +	 List<List<String>> testList=new LinkedList<>();
need to know the reason why you used LinkedList

2023-03-17 07:39 UTC, amitsahu8 commented on Assignment2/Assignment2.java
> +List<String>Elements=paths.get(i);
Variables should be camelcase

2023-03-24 12:23 UTC, tejashrighogare commented on Assignment1/Occurancesassign.java
> +		int count = 0;
Used parameterized method

2023-03-24 12:23 UTC, tejashrighogare commented on Assignment2/Assignment2.java
> +String inElement=Elements.get(1);
Done correction

2023-03-24 12:24 UTC, tejashrighogare commented on Assignment2/Assignment2.java
> +List<String>Elements=paths.get(i);
Done

2023-03-24 12:24 UTC, tejashrighogare commented on Assignment2/Assignment2.java
> +	 List<List<String>> testList=new LinkedList<>();
Used ArrayList.

2023-03-30 05:19 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 3/swapPrimeNo/swapPrimeNo.java
> +        SwapPrimeNumber(inputArray);
Use Multiple Input parameter.

2023-03-30 05:23 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 3/swapPrimeNo/swapPrimeNo.java
> +        }
No need to use loop for printing Array. Use  System.out.println(Arrays.toString(inputArray));

2023-03-30 05:39 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 7/ascendingOrderArray/ascendingOrderArray.java
> +        }
no need to print loop for prinit array

2023-03-30 05:42 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 4/stringMergeAlternativly/stringMergeAlternativly.java
> +        String result=   mergeStringAlternatively("abc", "xyz");
format the code using ctrl+alt+L

2023-03-30 05:42 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 2/Patterns/Patterns.java
> +            System.out.println();
why empty syout?

2023-03-30 05:56 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 1/taxSalary/taxSalary.java
> +            default: {
remove extra space

2023-03-30 05:58 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 1/taxSalary/taxSalary.java
> +        double tax = 0;
why using double? Practically salary will be in int. If the  calculated tax is in double format use rounding off.

2023-03-30 06:00 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/funOverloading.java
> +
remove extra space.

2023-03-31 09:58 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/CountOccurrenceOfChar.java
> +
remove extra space.

2023-03-31 10:15 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/Hashset1.java
> +public class Hashset1 {
Change Class name do not have Integer in it

2023-03-31 10:15 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/Hashset1.java
> +
remove extra space

2023-03-31 10:16 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/abstractClass.java
> +
remove extra space

2023-03-31 10:16 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/arrayJava.java
> +
remove extra space.

2023-03-31 10:17 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/arrayList_linkedList.java
> +public class arrayList_linkedList {
Class name first letter should be capital.

2023-03-31 10:17 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/dataTypes.java
> +public class dataTypes {
class first letter should be capital

2023-03-31 10:18 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/default_parameterized_constructor.java
> +class constructorClass {
Class first letter should be capital

2023-03-31 10:19 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/arrayList_linkedList.java
> +public class arrayList_linkedList {
Do not use Under Score in it Use camel case.

2023-03-31 10:28 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/equalsHashcode.java
> +    public static void main(String[] args) {
Please Remove Under score from class name.

2023-03-31 10:28 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/findDestination.java
> +public class findDestination {
First letter should be capital. in calss name

2023-03-31 10:29 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/forEach.java
> +    //Write program for foreach loop
First letter should be capital. in class name

2023-03-31 10:29 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/funOverloading.java
> +    //Program for functionOverloading
First letter should be capital. in class name

2023-03-31 10:29 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/funOverriding.java
> +    void run() {
First letter should be capital. in class name

2023-03-31 10:29 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/hashMap.java
> +	//Write program for hashMap
First letter should be capital. in class name

2023-03-31 10:30 UTC, rohitlamsonge66 commented on javaTutorialPrograms/java/Occurances/hierarchicalInheritance.java
> +    //Write program for hirarchical Inheritance
First letter should be capital. in class name

2023-04-03 07:05 UTC, rohitlamsonge66 commented on mediumDifficultyAll Pro/Medium difficulty Program 7/ascendingOrderArray/ascendingOrderArray.java
> +public class ascendingOrderArray {
Changes for all the class name.

2023-04-03 08:10 UTC, rohitlamsonge66 commented on JavaTutorialPrograms/java/Occurances/InterfaceJava.java
> +interface interfaceClass {
First letter Capital of interface name

2023-04-03 08:17 UTC, rohitlamsonge66 approved these changes

2023-04-03 10:40 UTC, amitsahu8 requested changes

2023-04-03 10:40 UTC, amitsahu8 commented on JavaTutorialPrograms/java/Occurances/AbstractClass.java
> +abstract class AbstarctClass {
public missing

2023-04-03 10:40 UTC, amitsahu8 commented on JavaTutorialPrograms/java/Occurances/CountOccurrenceOfChar.java
> +        boolean result = sameOccurrence_new("abcdabcd");
why sameOccurrence_new?
I already told not to use test, new, demo string

2023-04-03 10:40 UTC, amitsahu8 commented on JavaTutorialPrograms/java/Occurances/CountOccurrenceOfChar.java
> +            char c = inputString.charAt(counter);
why c?

2023-04-05 15:32 UTC, prashantkawa requested changes

2023-04-05 15:32 UTC, prashantkawa commented on JavaTutorialPrograms/java/findDestination/FindDestination.java
> +        cityList.add(listItemThird);
Use better approach to add values in the list

2023-04-05 15:32 UTC, prashantkawa commented on JavaTutorialPrograms/java/findDestination/FindDestination.java
> +            String inElement = stringElement;
no need of creating this variable

2023-04-05 15:32 UTC, prashantkawa commented on JavaTutorialPrograms/java/queueExample/Queue.java
> +    public static int queue[];
use private here

2023-04-05 15:32 UTC, prashantkawa commented on JavaTutorialPrograms/java/sortNumber/SortNumber.java
> +        }
No need to use for loop to print Array values, you can use Arrays.toString() method

2023-04-05 15:32 UTC, prashantkawa commented on JavaTutorialPrograms/java/staticVaribleExample/Student.java
> +    static String staticVariable = "ITS";
use private here

2023-04-05 15:32 UTC, prashantkawa commented on Medium Difficulty/Medium difficulty program 1/taxPackage/TaxSalary.java
> +                break;
write this logic in case 4 and use default for invalid input

2023-04-10 03:24 UTC, prashantkawa approved these changes
Approving PR

2023-04-10 08:18 UTC, prashantkawa approved these changes
Approving PR

2023-04-11 07:00 UTC, prashantkawa requested changes

2023-04-11 07:00 UTC, prashantkawa commented on swapPrimeNo/SwapPrimeNo.java
> +    private boolean flag = false;
Remove unused variables

2023-04-11 07:00 UTC, prashantkawa commented on swapPrimeNo/SwapPrimeNo.java
> +        boolean result = false;
Same here

2023-04-11 07:00 UTC, prashantkawa commented on swapPrimeNo/SwapPrimeNo.java
> +        swapPrimeNumber(lastNumber, 2);
No need to call this method here as it is already getting called in printResult method

2023-04-11 07:59 UTC, prashantkawa requested changes

2023-04-11 07:59 UTC, prashantkawa commented on Medium Difficulty/Medium difficulty program 3/SwapPrimeNo/SwapPrimeNo.java
>      private int lastNumber;
please remove this variables if not in use

2023-04-11 10:43 UTC, prashantkawa approved these changes
Approving PR

2023-04-11 10:43 UTC, merged