Added Java Coding Program 10
tejashrighogare/SDETAssignment pull request #21
Opened 2023-05-17 09:13 UTC by tejashrighogare

2023-05-18 08:35 UTC, amitsahu8 requested changes

2023-05-18 08:35 UTC, amitsahu8 commented on swapCharacter/SwapCharacterProgram.java
> +        int count = 3;
use proper variable as per the usage

2023-05-19 07:04 UTC, tejashrighogare commented on swapCharacter/SwapCharacterProgram.java
> +        int count = 3;
Used proper variable name

2023-05-22 09:28 UTC, amitsahu8 requested changes

2023-05-22 09:28 UTC, amitsahu8 commented on swapCharacter/SwapCharacterProgram.java
> +        int characterCounter = 3;
understand the variable usage and give the name accordingly.

2023-05-25 14:42 UTC, amitsahu8 approved these changes

2023-05-25 14:43 UTC, merged